### ISSUE TITLE
站点支持反馈

### ISSUE THREAD

**Issue by fsaimon** [alex8224/web2mpv#2]
「优酷」 ok（并不看优酷。。。
「http://www.bilibili.com/video/avxxxx/」 ok
「http://bangumi.bilibili.com/anime/v/xxxx」 fail
「YouTube」 fail
「niconico」 fail

OS：macOS
Chrome：web2mpv插件
app：W2mpv.app/mpv.app
brew：you-get/youtube-dl/nicovideo-dl
都是最新版本的。

**Comment by alex8224** [comment]
http://bangumi.bilibili.com/anime/v/xxxx 的问题请参考 https://github.com/soimort/you-get/issues/1436 
活着在cli使用如下命令看能否执行成功 
```shell
     you-get http://xxxx/nnnn
```

web2mpv只是简单的调用you-get ~

**Comment by alex8224** [comment]
http://bangumi.bilibili.com/anime/v/xxxx 的问题请参考 https://github.com/soimort/you-get/issues/1436 
或者在cli使用如下命令看能否执行成功 

``` shell
     you-get http://xxxx/nnnn
```

web2mpv只是简单的调用you-get ~

**Comment by fsaimon** [comment]
B站番的问题似乎是这个 [soimort/you-get#1449](https://github.com/soimort/you-get/issues/1449)
 cli下依旧失败
另外，刚才测试了 YouTube 可以通过cli下载，但是却不能通过web2mpv观看，niconico没有测。

**Comment by alex8224** [comment]
好的，
你是直接连接的还是用代理啊在命令行？
我这里上不了youtube，等我能上了看看。

FS notifications@github.com于2016年10月30日周日 下午6:28写道：

**Comment by fsaimon** [comment]
嗯 设置了代理的

**Comment by alex8224** [comment]
web2mpv在调用命令行的时候没有加代理参数，默认你的系统必须能够直连才行，或者你的路由器配置了透明代理。

FS notifications@github.com于2016年10月30日周日 下午7:41写道：
